=== gokulsam07/Airlines-Cucumber-RestAssured/airlines/src/test/java/testdata/airlineOutputSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "number"
      },
      "name": {
        "type": "string"
      },
      "country": {
        "type": "string"
      },
      "logo": {
        "type": "string"
      },
      "slogan": {
        "type": "string"
      },
      "head_quaters": {
        "type": "string"
      },
      "website": {
        "type": "string"
      },
      "established": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "name",
      "country",
      "logo",
      "slogan",
      "head_quaters",
      "website",
      "established"
    ]
  }
}

=== gokulsam07/Airlines-Cucumber-RestAssured/airlines/src/test/java/testdata/createAirline.json
{
        "id": 5000,
        "name": "Alaska Airways",
        "country": "USA",
        "logo": "https://upload.wikimedia.org/wikipedia/en/thumb/9/9b/Alaksa_Airlines.png",
        "slogan": "Fly High",
        "head_quaters": "Alaska",
        "website": "www.alaskaairlines.com",
        "established": "1994"
    }
